name: Build the project to check if it is broken

on:
  pull_request:
    branches: [ "main" ]

# Allow one concurrent deployment
concurrency:
  group: "pr"
  cancel-in-progress: true
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 23.x
      uses: actions/setup-node@v3
      with:
        node-version: 23.x
        cache: 'npm'
    - run: npm ci
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    - run: npm run build --if-present
    env:
      NODE_OPTIONS: --openssl-legacy-provider
